name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: PHPCodeSniffer
      uses: rtCamp/action-phpcs-inspection@v1.0.0
